Back 2/Controllers/ContactController.cs
using RiccoTest2.Models;
using System;
using System.ComponentModel;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace RiccoTest2.Controllers
{
    public class ContactController : Controller

    {

        //uses the System.Net.Mail Name space
        private SmtpClient smtpClient;

        [HttpGet]
        public ActionResult Index()
        {

            MailModel Model = new MailModel()
            {
                AccountName = "amelia@barnvaal.co.za",
                AccountPassword = "@MyLogin007",
                SMTP_HOST = "webmail.barnvaal.co.za",
                SMTP_PORT = 25,
                MessageBody = "",
                MessageSubject = "Customer Enquiry - From Web Site",
                FromAddress = "",
                ToAddress = "amelia@barnvaal.co.za",//"Riccoassasin@gmail.com",
                ContactPerson = "",
                ContactNumber = ""


            };


            return View(Model);
        }


        [HttpPost]
        public ActionResult Index(MailModel Model)
        {

            if (ModelState.IsValid)
            {
                smtpClient = new SmtpClient(Model.SMTP_HOST, Model.SMTP_PORT);

                System.Net.NetworkCredential credentials = new System.Net.NetworkCredential(Model.AccountName, Model.AccountPassword);

                // smtpClient.Credentials = credentials;
                //smtpClient.UseDefaultCredentials = true;

                // Specify the email sender.
                // Create a mailing address that includes a UTF8 character
                // in the display name.
                MailAddress from = new MailAddress(Model.FromAddress);

                // Set destinations for the email message.
                MailAddress to = new MailAddress(Model.ToAddress);
                // Specify the message content.
                MailMessage message = new MailMessage(from, to);


                message.Body = Model.MessageBody + "\n From: " + Model.ContactPerson + " \n  Conatct Number is: " + Model.ContactNumber;

                message.Subject = Model.MessageSubject;

                // smtpClient.SendCompleted += new SendCompletedEventHandler(SendCompletedCallback);
                // The userState can be any object that allows your callback 
                // method to identify this send operation.
                // For this example, the userToken is a string constant.
                //string userState = "ThisCanBeAnyThingYouWant";
                smtpClient.Send(message);
                // Clean up.
                message.Dispose();

                return RedirectToAction("Index");
            }
            else
            {
                if (Model.ContactPerson is null)
                {
                    Model.ContactPerson = "";
                }
                if (Model.MessageBody is null)
                {
                    Model.MessageBody = "";
                }
                if (Model.ContactNumber is null)
                {
                    Model.ContactNumber = "";
                }
                if (Model.FromAddress is null)
                {
                    Model.FromAddress = "";
                }
            }
            return View(Model);

        }

        static bool mailSent = false;

        private static void SendCompletedCallback(object sender, AsyncCompletedEventArgs e)
        {
            // Get the unique identifier for this asynchronous operation.
            String token = (string)e.UserState;


            if (e.Error != null)
            {
                //Pop up error message
                string x = "";
            }
            else
            {
                // popup  successfully sent mesasage
                String dd = "";
            }
            mailSent = true;
        }


        protected override void Dispose(bool disposing)
        {
            //this.smtpClient.Dispose();
            base.Dispose(disposing);
        }

    }
}

Back 2/Controllers/PhotoGalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RiccoTest2.Controllers
{
    public class PhotoGalleryController : Controller
    {
        // GET: PhotoGallery
        public ActionResult Index()
        {
            return View();
        }
    }
}

Back 2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title</title>
    <!-- Bootstrap core CSS -->
    <link href="@Url.Content("~/css/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("~/css/business-casual.css")" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

    <div class="brand"></div>
    <div class="address-bar text-center"><img src="~/img/hp.jpg" style="max-height:500px;max-width:500px; border: solid;" class="img-rounded" /></div>

    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Business Casual</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Home", "Index", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("About", "Index", "About")
                    </li>
                    <li>
                        @Html.ActionLink("Photo Gallery", "Index", "PhotoGallery")
                    </li>
                    <li>
                        @Html.ActionLink("Contact Us", "Index", "Contact")
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    @RenderBody()

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; The Barn @DateTime.Now.Year.ToString()</p>
                </div>
            </div>
        </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="@Url.Content("~/js/bootstrap.js")"></script>
    @RenderSection("scripts", false)
</body>
</html>